### PR TITLE
Add missing public api docs

### PR DESCRIPTION
**Pull request by comatory**

### CODE REVIEW

**Review by JaffaKetchup — APPROVED** [review]
Looking good! It's ok to merge to this branch first if you want, then to this fork. (In response to your comment on Documentation Improvements)

**Comment by comatory** [comment]
On Wed Jan 12, 2022 at 4:40 PM CET, Luka S wrote:
> @JaffaKetchup approved this pull request.
>
> Looking good! If you can merge, please feel free to. Thanks!

You don't have any code review set up in this repo (approvers)?
I'm fine with merging it although I want to go through the exported
code again and see if there's some low hanging fruit in terms of API
docs that I could grab.

There's a failing check for me due to Vercel not being able to generate
review app (for doc webpage I assume). @JaffaKetchup is it something
I need to configure in my fork?

**Comment by JaffaKetchup** [comment]
No, no approvers, as it was originally just us.

You don't have to merge now, if you want to do other stuff, that's a good idea not to merge now.

I didn't setup Vercel, the other person did, so I'm not sure what to do. I'm on mobile at the moment, so I can have a look later if necessary.

**Comment by themisir** [comment]
My the way we can setup a temporary github org to manage access controls. Github personal repository access controls are limited and I don't want to limit your expression 😅 So if it's okay with you I would like to create an org and migrate this repo(fork) to there.

**Comment by JaffaKetchup** [comment]
Sounds good to me, as long as it can be done 'cleanly'.

**Pull request merged**
