### PR TITLE
feature: add specs to bounds data model

### PR DESCRIPTION
**Pull request by comatory**

### CODE REVIEW

**Comment by comatory** [comment]
It seems like branch rules are not set up for this repository, it'd be great if the actions could be ran on each PR.

**Comment by JaffaKetchup** [comment]
Again, the owner would have to set this up. I think they intend to put this into a organisation temporarily to more easily manage permissions, see https://github.com/themisir/flutter_map/pull/3#issuecomment-1011338990?

I'm not quite confident with messing with actions and deployments just yet, especially on something like this, where what we/I do could directly impact a big project (flutter_map) in the end.

**Comment by themisir** [comment]
> It seems like branch rules are not set up for this repository, it'd be great if the actions could be ran on each PR.

Actions was created by flutter_map maintainers. I could propose another PR into the main repo to run actions on all branches.

**Comment by comatory** [comment]
@JaffaKetchup would be nice to merge this into upstream as well

**Comment by JaffaKetchup** [comment]
I agree, and I would if I could, but I'm not sure how to merge this to 'flutter_map' (if that's what you mean as upstream) now it's been merged to here.

**Comment by JaffaKetchup** [comment]
If you were to make another PR for this same branch to be merged to 'flutter_map', maybe that would work?

**Comment by comatory** [comment]
On Sat Jan 29, 2022 at 3:57 PM CET, Luka S wrote:
> If you were to make another PR for this same branch to be merged to 'flutter_map', maybe that would work?
>

Yeah sure no problem.

**Pull request merged**
